"""
Rules-layer classifier — pure functions over a single message text.

Loads YAML pattern files once at import; exposes:
    classify(text) -> {intent, topic, tone, identifiers}

Where identifiers is a list of {kind, name} dicts (deduped within msg).

No DB dependency — caller (processors.run) handles persistence.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
RULES_DIR = Path(__file__).resolve().parent / "rules"


# ----------------------------------------------------------------------
# Pattern compilation
# ----------------------------------------------------------------------

@dataclass
class Pattern:
    raw: str
    regex: re.Pattern
    weight: float = 1.0


@dataclass
class LabelSet:
    """A category (intent/topic/tone) → list of label-keyed pattern bundles."""
    name: str
    labels: dict[str, list[Pattern]] = field(default_factory=dict)

    @classmethod
    def load(cls, path: Path, category: str) -> "LabelSet":
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        ls = cls(name=category)
        for label, body in data.items():
            patterns = body.get("patterns", []) if isinstance(body, dict) else []
            compiled: list[Pattern] = []
            for p in patterns:
                if not p:
                    continue
                # Auto-flag IGNORECASE unless pattern contains local / non-ASCII (which is already case-less)
                flags = re.IGNORECASE if all(ord(c) < 0x80 for c in p) else 0
                try:
                    compiled.append(Pattern(raw=p, regex=re.compile(p, flags)))
                except re.error as e:
                    print(f"[rules:{category}/{label}] bad regex {p!r}: {e}")
            ls.labels[label] = compiled
        return ls


@dataclass
class IdentifierExtractor:
    name: str
    regex: re.Pattern
    kind: str
    normalize: list[str] = field(default_factory=list)


def _load_identifiers(*paths: Path) -> list[IdentifierExtractor]:
    """Load identifier extractors from one or more YAML files. Later files merge
    on top of earlier ones — duplicate group names append, they do NOT overwrite."""
    out: list[IdentifierExtractor] = []
    for path in paths:
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        for group, items in data.items():
            if not items:
                continue
            for item in items:
                if not isinstance(item, dict):
                    continue
                try:
                    rx = re.compile(item["regex"], re.IGNORECASE)
                except re.error as e:
                    print(f"[identifiers:{group}] bad regex {item['regex']!r}: {e}")
                    continue
                out.append(IdentifierExtractor(
                    name=group,
                    regex=rx,
                    kind=item.get("kind", group),
                    normalize=item.get("normalize", []),
                ))
    return out


@lru_cache(maxsize=1)
def _rules() -> dict[str, Any]:
    return {
        "intent": LabelSet.load(RULES_DIR / "intent.yaml", "intent"),
        "topic":  LabelSet.load(RULES_DIR / "topic.yaml",  "topic"),
        "tone":   LabelSet.load(RULES_DIR / "tone.yaml",   "tone"),
        "identifiers": _load_identifiers(
            RULES_DIR / "identifiers.yaml",
            RULES_DIR / "brands.yaml",  # generated by scripts/seed_operators.py
        ),
    }


# ----------------------------------------------------------------------
# Classification
# ----------------------------------------------------------------------

def _score_labels(text: str, ls: LabelSet) -> tuple[str | None, dict[str, float]]:
    """Return (top_label_or_None, full_score_vector)."""
    scores: dict[str, float] = {}
    for label, patterns in ls.labels.items():
        s = 0.0
        for p in patterns:
            if p.regex.search(text):
                s += p.weight
        if s > 0:
            scores[label] = s
    if not scores:
        return None, {}
    # Tie-break by YAML order (insertion order preserved); take label with highest score,
    # earliest in YAML on tie.
    label_order = list(ls.labels.keys())
    top = max(scores.items(), key=lambda kv: (kv[1], -label_order.index(kv[0])))
    return top[0], scores


def _normalize(value: str, ops: list[str]) -> str:
    v = value
    for op in ops:
        if op.startswith("force:"):
            # Override captured value with literal canonical (used by brand patterns
            # that match many surface forms — "examplebet"/"examplebet168"/"examplebet-local"
            # all collapse to a single canonical entity name).
            v = op.split(":", 1)[1]
        elif op == "strip_spaces":
            v = re.sub(r"\s+", "", v)
        elif op == "strip_dashes":
            v = v.replace("-", "")
        elif op == "lower":
            v = v.lower()
        elif op == "e164_local":
            # Example phone normalizer: convert local 0-prefixed numbers to E.164.
            # The "66" country code is a placeholder — replace with YOUR instance's
            # calling code (and rename the op consistently in the yaml + here) when
            # populating the template for a real (country × domain) instance.
            example_cc = "66"
            digits = re.sub(r"\D", "", v)
            if digits.startswith(example_cc):
                v = "+" + digits
            elif digits.startswith("0"):
                v = "+" + example_cc + digits[1:]
            else:
                v = "+" + example_cc + digits
    return v


def extract_identifiers(text: str) -> list[dict]:
    """Return list of {kind, name, raw} dicts. Within-msg dedupe by (kind, name)."""
    out: dict[tuple[str, str], dict] = {}
    if not text:
        return []
    for ex in _rules()["identifiers"]:
        for m in ex.regex.finditer(text):
            raw = m.group(1) if m.groups() else m.group(0)
            if not raw:
                continue
            normed = _normalize(raw, ex.normalize)
            if not normed or len(normed) < 2:
                continue
            key = (ex.kind, normed)
            if key not in out:
                out[key] = {"kind": ex.kind, "name": normed, "raw": raw}
    return list(out.values())


def classify(text: str | None) -> dict:
    """Score a single message text. Returns {intent, topic, tone, identifiers}."""
    if not text:
        return {"intent": None, "topic": None, "tone": None,
                "intent_scores": {}, "topic_scores": {}, "tone_scores": {},
                "identifiers": []}
    rules = _rules()
    intent, intent_scores = _score_labels(text, rules["intent"])
    topic,  topic_scores  = _score_labels(text, rules["topic"])
    tone,   tone_scores   = _score_labels(text, rules["tone"])
    return {
        "intent": intent,
        "topic": topic,
        "tone": tone,
        "intent_scores": intent_scores,
        "topic_scores": topic_scores,
        "tone_scores": tone_scores,
        "identifiers": extract_identifiers(text),
    }


if __name__ == "__main__":
    # Generic English demo strings exercising each classifier category +
    # identifier extractor. Replace with locked-instance source-language
    # samples when validating per-instance rule files.
    samples = [
        "Deposit 100 get 200, promo today only!! chat: @slotbrand-a promo code: WELCOME99",
        "Hot pick draw 16/11 sure win 17 84 wallet +10812345678",
        "Police raid on betting site examplebet, site blocked!",
        "Agent wanted, income 50000 per month, chat: @recruit-bola",
        "Promo free signup at casino, examplebank 1234567890",
    ]
    import json
    for s in samples:
        r = classify(s)
        print("---")
        print(s)
        print(json.dumps({"intent": r["intent"], "topic": r["topic"], "tone": r["tone"],
                          "ids": r["identifiers"]}, ensure_ascii=False))
